### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by hdjsjyl** [EricGuo5513/momask-codes#11]
Hi Author,
    When I run the python gen_t2m.py --gpu_id 2 --ext exp1 --text_prompt "A person is running on a treadmill.", I meet the following error:

MovieWriter stderr:
[libopenh264 @ 0x55aad87a7f00] Incorrect library version loaded
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

Traceback (most recent call last):
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 236, in saving
    yield self
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 1177, in save
    writer.grab_frame(**savefig_kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 357, in grab_frame
    dpi=self.dpi, **savefig_kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2261, in print_figure
    **kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 455, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gen_t2m.py", line 258, in <module>
    plot_3d_motion(ik_save_path, kinematic_chain, ik_joint, title=caption, fps=20)
  File "/home/shilei/projects/momask-codes/utils/plot_script.py", line 411, in plot_3d_motion
    ani.save(save_path, fps=fps)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 1177, in save
    writer.grab_frame(**savefig_kwargs)
  File "/opt/conda/envs/momask/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 347, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "/opt/conda/envs/momask/lib/python3.7/site-packages/matplotlib/animation.py", line 379, in _cleanup
    self._proc.returncode, self._proc.args, out, err)
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '1000x1000', '-pix_fmt', 'rgba', '-r', '20', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', './generation/exp1/animations/0/sample0_repeat0_len196_ik.mp4']' returned non-zero exit status 1.

Any suggestions?

**Comment by Chatonz** [comment]
i have the same problem. how do you solve this？

**Comment by randomx207** [comment]
hello! Do you know how to solve this issue?

**Comment by jidongkuang** [comment]
@hdjsjyl Could you please tell me how you solved this problem?
