### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './glove/our_vab_data.npy'

### ISSUE THREAD

**Issue by shuowang666** [EricGuo5513/momask-codes#34]
Loading dataset kit ...
Traceback (most recent call last):
  File "train_vq.py", line 114, in <module>
    eval_val_loader, _ = get_dataset_motion_loader(dataset_opt_path, 32, 'test', device=opt.device)
  File "/fuxi_team14/users/leifwang/code/momask-codes/motion_loaders/dataset_motion_loader.py", line 18, in get_dataset_motion_loader
    w_vectorizer = WordVectorizer('./glove', 'our_vab')
  File "/fuxi_team14/users/leifwang/code/momask-codes/utils/word_vectorizer.py", line 48, in __init__
    vectors = np.load(pjoin(meta_root, '%s_data.npy'%prefix))
  File "/data/home/leifwang/anaconda3/envs/momask/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './glove/our_vab_data.npy'

Hello, I made this mistake during training, where can I get this file? (/glove/our_vab_data.npy)

**Comment by CuiYX03** [comment]
In README.md     Get You Ready    2. Models and Dependencies, I think you should run 
bash prepare/download_glove.sh 
to download the folder glove.
