### ISSUE TITLE
 'Namespace' object has no attribute 'dim_movement_enc_hidden'

### ISSUE THREAD

**Issue by LGZ-BIT** [EricGuo5513/momask-codes#94]
Hi, thanks for your great work for community.!
But when I wanted to re-train the RVQ using the command released, some errors occurred.
Traceback (most recent call last):
  File "/home/user/grad_proj/momask-codes/train_vq.py", line 79, in <module>
    eval_wrapper = EvaluatorModelWrapper(wrapper_opt)
  File "/home/user/grad_proj/momask-codes/models/t2m_eval_wrapper.py", line 48, in __init__
    self.text_encoder, self.motion_encoder, self.movement_encoder = build_models(opt)
  File "/home/user/grad_proj/momask-codes/models/t2m_eval_wrapper.py", line 6, in build_models
    movement_enc = MovementConvEncoder(opt.dim_pose-4, opt.dim_movement_enc_hidden, opt.dim_movement_latent)
AttributeError: 'Namespace' object has no attribute 'dim_movement_enc_hidden'

Do you have any idea about this problem?

**Comment by 1997MarsRover** [comment]
Hello @LGZ-BIT were you able to fix this, since am getting the same error
